name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          fw-dummy
          # fw-static-analysis,
          # fw-quality-analysis,
          # fw-security-analysis,
          # fw-doc,
          # fw-build,
          # fw-unit-test,
          # fw-component-test,
          # fw-integration-test,
          # fw-system-test,
          # fw-deploy-testbench,
          # fw-system-e2e,
          # fw-acceptance,
          # fw-report,
          # fw-release
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GHCR Logging
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ./${{ matrix.image }}/Dockerfile \
            --tag $IMAGE_NAME:latest \
            --push \
            ./${{ matrix.image }}
