name: GHCR Docker Builder & Publisher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [fw-dummy, fw-arm-builder]
        os: [linux]
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          
          # Split platform into OS and ARCH in Bash
          PLATFORM=${{ matrix.os }}
          ARCH=${{ matrix.arch }}
          
          #DOCKERFILE=Dockerfile.$PLATFORM
          DOCKERFILE=Dockerfile


          echo "Building for $PLATFORM/$ARCH..."
          
          docker buildx build \
            --platform ${{ matrix.os }}/$ARCH \
            --build-arg PLATFORM=$PLATFORM \
            --build-arg ARCH=$ARCH \
            -f ./${{ matrix.image }}/$DOCKERFILE \
            -t $IMAGE_NAME:latest \
            --push ./${{ matrix.image }}
